# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d47277756f05010485d031012b084573"
organization_id = "1981797"
name = "Collection Sort V69"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,read_orders,read_all_orders"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
